server:
  port: 9001

spring:
  application:
    name: index12306-user${unique-name:}-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host:
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr:
        password: nacos
        username: nacos